import os

Import('TOP')
OUTPUT_LIB_DIR = TOP['OUTPUT_LIB_DIR']
HAL_LIB_DIR = os.path.join(OUTPUT_LIB_DIR, 'hal', 'libhal.a')

LOCAL_PATH = Dir('.').srcnode().abspath

lib_src = Glob("src/*.c")
lib_inc = os.path.join(LOCAL_PATH, 'include')

TOP['HAL'] = {}
TOP['HAL']['SRC'] = lib_src
TOP['HAL']['INC_DIRS'] = [lib_inc]
TOP['INC_DIRS'].append(lib_inc)
TOP['LIB_DIRS'].append(HAL_LIB_DIR)

Library(
    target = "hal",
    source = lib_src,
    CPPPATH = lib_inc
)

